version: '3.6'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ddev-${DDEV_SITENAME}-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db